### ISSUE TITLE
Summit+Worldmeeting Travel

### ISSUE THREAD

**Issue by brigitteschuckert** [hansd/gradle-admin-private#4]
Confirm that this list ist final and we can go ahead and book for all non-speakers. Let us know if there is any planned termination or any other reason that prevents us from booking travel.  https://docs.google.com/a/gradle.com/spreadsheets/d/1ba2Snq_p812IMpqpJ4py8lSIe1rN3cxxo0BvbLYoTJg/edit?usp=sharing

**Comment by hansd** [comment]
This is confirmed.
