### ISSUE TITLE
Salary increase

### ISSUE THREAD

**Issue by brigitteschuckert** [hansd/gradle-admin-private#6]
Wir müssen nochmal über die Lohnerhöhungen sprechen. Das Google Sheet "Salary Increases" von StefanH ist für mich an manchen Stellen nicht ausreichend. 
- Cedric: Erhöhung muss größer 0% sein, da er mir auch gesagt hat, dass er mehr bekommt. 
- Stefan O: Bestätige bitte die im Vgl. zu anderen sehr hohe Lohnerhöhung sowie Zeitpunkt
- Lorant: ok - er hat seine März Rechn. schon angepasst.
- Eric: Bitte bestätige Lohnerhöhung und Zeitpunkt
- Luke: er hat seine Rechn. für März nicht erhöht. Bitte Info zu Zeitpunkt und Erhöhung. 
Danke.

**Comment by hansd** [comment]
Luke: Ist OK zum nächsten Monat.
Eric: Nächstmöglich
Stefan: Ist OK. Er hat eine Führungsposition und macht einen super Job. 
Cedric: Muss ich noch klären.

**Comment by hansd** [comment]
Cedric bekommt eine Erhöhung auf 90K und 0.5 mal mehr Shares (ca 8000)
